### ISSUE TITLE
无法通过git lfs来下载“2021年（上半年）Rust语言中文精选.pdf”

### ISSUE THREAD

**Issue by 2moe** [RustMagazine/rust_magazine_2021#114]
![2021-07-17 20-39-08屏幕截图](https://user-images.githubusercontent.com/25324935/126037326-994bea6a-6340-476e-ae72-551c4ebb7c11.png)
> git lfs fetch
```                                                                
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/RustMagazine/rust_magazine_2021.git/info/lfs'
```
github的lfs每月应该有[流量限制](https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage)，超出流量后可能无法下载。
___
我建议您将pdf文件放在[releases](https://github.com/RustMagazine/rust_magazine_2021/releases)处，这样可以方便大家下载，谢谢。

**Comment by ZhangHanDong** [comment]
@2moe ok，我抽空上传到 releases
