### ISSUE TITLE
报名编辑组

### ISSUE THREAD

**Issue by suhanyujie** [RustMagazine/rust_magazine_2021#12]
笔名：亡命之徒
性别：男
爱好：Rust/Go/PHP
联系方式：suhanyujie@qq.com
简介：喜欢 Rust，熟练 markdown 语法，并翻译过一些 Rust 文章，有自己的 Rust [翻译仓库](https://github.com/suhanyujie/article-transfer-rs)。

**Comment by ZhangHanDong** [comment]
@suhanyujie 你在Rust社区微信群里吗（任意一个）？加一下我的微信。

**Comment by suhanyujie** [comment]
这个 issue 我先关掉。但其他 coder 还是可以查阅的。
主要记录一下入社群的过程：

* 联系 @ZhangHanDong ，微信加好友。
* 由 @ZhangHanDong  老师拉你进群。
* 开始工作。
