### ISSUE TITLE
八月刊，pager Rudra，三个图没放。

### ISSUE THREAD

**Issue by LooJee** [RustMagazine/rust_magazine_2021#127]
![image](https://user-images.githubusercontent.com/13059033/131597590-ea13e07f-60f8-44b5-80e4-6be600ac7103.png)
![image](https://user-images.githubusercontent.com/13059033/131597637-0d8b2466-7f75-4ab5-be9e-fc70b08ec389.png)
![image](https://user-images.githubusercontent.com/13059033/131597662-b0b6d846-86ee-4c4a-80bd-8a2e42f54d45.png)

**Comment by ZhangHanDong** [comment]
噢，感谢反馈

**Comment by ZhangHanDong** [comment]
已修复。
