### ISSUE TITLE
惋惜

### ISSUE THREAD

**Issue by jonZ92** [RustMagazine/rust_magazine_2021#177]
很棒的期刊，什么原因不在继续了？

**Comment by ZhangHanDong** [comment]
@jonZ92 感谢喜欢。

不继续有很多原因：
1. 时间不充裕
2. 小黑子喷我
3. 投稿不积极
4. 其他

**Comment by ZhangHanDong** [comment]
现在有新的期刊，由 @Folyd 主导，  https://rustmagazine.org/ ，欢迎关注

**Comment by whereiszebra** [comment]
沉痛悼念中文唯一rust期刊

**Comment by whereiszebra** [comment]
默哀
