### ISSUE TITLE
UML图片分辨率低 - 文章《图解Rust所有权与生命周期》 图7 生命周期

### ISSUE THREAD

**Issue by birdinforest** [RustMagazine/rust_magazine_2021#28]
文件：https://github.com/RustMagazine/rust_magazine_2021/blob/main/src/chapter_1/rust_ownership/rust_ownership_7.jpg
因为分辨率低，无法看清文本。

因为之前有包含全部概念的总图，所以并不影响文章理解。

我尝试过从总图中截出一份生命周期的UML图，以便提交PR，但是感觉这样修改出来的不够完美。如果作者有时间的话，希望能重新导出一份高分辨率的图片。

谢谢。

**Comment by ZhangHanDong** [comment]
目前只有总图是高分辨率的，作者的目的是让你去看总图

**Comment by birdinforest** [comment]
@ZhangHanDong 是的，总图的分辨率很高。我没有比较其它插图的分辨率，可能比总图低。但是其它的插图中的文字可以被识别，上面提到的那张图的分辨率不足以识别文字。

我不认为作者的目的是让读者看总图，因为总图之外的插图中有额外的注释，以及代码片段。所以在可能的情况下，还是希望能够更新以下图片。

**Comment by ZhangHanDong** [comment]
@bingryan  

1. 这篇文章最初只有一张总图，并没有文字，是我和作者见面的时候他手机里的存图
2. 总图和截图都是作者自己弄的
3. 我也没有图7的清晰图片
4. 有空我会找作者要一下有没有图7的清晰图，有的话就更新，没有就不更新。
5. 这个话题可以关闭了。

**Comment by ZhangHanDong** [comment]
@bingryan 图片已更新：https://github.com/RustMagazine/rust_magazine_2021/pull/42
