### ISSUE TITLE
这里的文章可以转载吗

### ISSUE THREAD

**Issue by iamazy** [RustMagazine/rust_magazine_2021#61]

**Comment by iamazy** [comment]
没看到readme最下角，请忽略

**Comment by ZhangHanDong** [comment]
@iamazy 完整地写明出处、加上原链接。

**Comment by iamazy** [comment]
@ZhangHanDong ，[Rust 中的 Arenas](https://github.com/fucking-translation/blog/blob/main/lang/rust/06-Rust%E4%B8%AD%E7%9A%84Arenas.md) 我是这样转的，如有不妥请告知

**Comment by ZhangHanDong** [comment]
可以
