### ISSUE TITLE
投稿 | Rust 学习系列

### ISSUE THREAD

**Issue by Celthi** [RustMagazine/rust_magazine_2021#63]
这篇文章记录自己的思考，希望分享给同样困扰的同学
https://zhuanlan.zhihu.com/p/360342782

**Comment by ZhangHanDong** [comment]
@Celthi 感谢投稿。

看了你这篇文章，写的不错，但不是月刊期望的文章。

月刊期望征集的是针对某个概念/领域的应用或深入思考性的文章，你这个文章知识点比较零散。

不过你这个文章，可以把里面讲到的让人困惑的点，拆分出来，发布到这里：https://rust-zh.github.io/faq/ 

这个 FAQ，我会每期摘两个点到月刊上面。

期待你后续的投稿。
